### ISSUE TITLE
Install all Tier 1 RMWs in containers

### ISSUE THREAD

**Issue by SteveMacenski** [ros-tooling/setup-ros-docker#58]
## Description

I'm looking to test code in a matrix with all Tier 1 RMWs. Currently only the default is installed so I can't simply change `env` in actions to use the one I desire. That seems easier than needing to compile each other RMW (e.g. cyclone) alongside the code every workflow by including it in a repos file since its not a strict `package.xml` dependency. 

## Completion Criteria

Update the docker containers to include all Tier 1 supported RMWs

**Comment by SteveMacenski** [comment]
Or -- analogously, have the default examples have the steps
```
    - name: Install Tier 1 DDS
      run: sudo apt install ros-iron-rmw-cyclonedds-cpp ... -y
```

In them so its immediately clear. Perhaps also explicitly set the env var too to make it clear to folks the workflow to get what they want out of the box without thinking.

**Comment by christophebedard** [comment]
#59 installs the other Tier 1 DDS implementation in the non-base Ubuntu images. I moved your suggestion to the `action-ros-ci` repo: https://github.com/ros-tooling/action-ros-ci/issues/838
