### ISSUE TITLE
Retrieve ownership of Docker Hub rostooling account

### ISSUE THREAD

**Issue by christophebedard** [ros-tooling/setup-ros-docker#62]
I do not have access to this account: https://hub.docker.com/u/rostooling. We still have the username and password as secrets in this repo, but it looks like we're having issues with it: https://github.com/ros-tooling/setup-ros-docker/pull/61#issuecomment-1837214098.

@emersonknapp do you know who has access to this account? I'm assuming it was someone from AWS a few years ago.

Another solution would be to stop publishing to Docker Hub and just use the GitHub Docker registry. We would have to announce this, somehow.

**Comment by christophebedard** [comment]
> do you know who has access to this account? I'm assuming it was someone from AWS a few years ago.

@thomas-moulard from the git history, it looks like this might be you.

**Comment by emersonknapp** [comment]
Yeah, I have ownership over the `rostooling` org on docker hub. It's connected to my personal account. I can add you. But I also agree that using github docker registry would be a nice way to go

**Comment by christophebedard** [comment]
I think it would be good to be able to manage it in the meantime. My Docker Hub username is the same: https://hub.docker.com/u/christophebedard

**Comment by christophebedard** [comment]
Thanks Emerson, I have access now. I'll close this.

> But I also agree that using github docker registry would be a nice way to go

I've opened #64 for this. I did realize that there wasn't really an issue with Docker Hub in #61; the issue was because the PR was coming from a fork.
