### ISSUE TITLE
Publish ARM images

### ISSUE THREAD

**Issue by emersonknapp** [ros-tooling/setup-ros-docker#65]
## Description

Newer MacBooks (and other laptops) are now using ARM processors, and so these base images don't support that by default - though they can with emulation but this is considerably slower than using an ARM images.
Additionally, many robot target platforms use ARM, so it would be useful to provide CI environments matching the target architecture.

We should create and push ARM images in parallel to the x86 ones that we are currently publishing.

We'd like to create ARM 

## Related Issues

N/A

## Completion Criteria

ARM versions of all images are pushed as part of standard build.

## Implementation Notes / Suggestions

I don't think there are GitHub Actions ARM runners available out of the box. Could possibly just trust a slower QEMU build to get the job done.

## Testing Notes / Suggestions

N/A

**Comment by christophebedard** [comment]
> Could possibly just trust a slower QEMU build to get the job done.

Yeah, this is pretty easy to do using `docker buildx`.

**Comment by christophebedard** [comment]
@emersonknapp FYI, looks like we already did this based on your request 😜
